name: auto_wallpager
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.0

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  path: ^1.9.0
  win32: ^5.15.0
  web_socket: ^1.0.1
  dio : ^5.9.0
  uuid: ^4.5.2
  collection: ^1.19.1
  json_annotation: ^4.9.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  logger: ^2.6.2
dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
  build_runner: ^2.10.4
  json_serializable: ^6.11.1
